#!/usr/bin/env bash
# This script displays "Best School" 10 times and "Hi" after the 9th time
i=1
while [ $i -le 10 ]
do
    echo "Best School"

    if [ $i == 9 ]
    then
	echo "Hi"
    fi

    ((i++))
done
